spring.application.name=ecommmerce
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}

user.url=${LOGIN_API_PORT}
server.port=8081